### ISSUE TITLE
sdk folder usage

### ISSUE THREAD

**Issue by yamashi** [cursey/ue4genny#3]
Hello,

I generated a SDK for a test game, it seems complete, but when I include it in a project I get thousands of build errors, does it expect the UE4 source to be available as well? Is it not production ready?

Thanks!

**Comment by cursey** [comment]
You're expected implement the necessary types that do not get generated yourself (they should be fairly simple, eg. `TArray`). Just make sure they have the same layout as the version used by the game you're targeting.

**Comment by yamashi** [comment]
Yeah I figured after tinkering with it, made some changes to get it to build more easily and can confirm that it works perfectly after going through the process! 
This is really awesome, coming from games that lack metadata this is pretty amazing!
